//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE_Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>rmyMbnSYwJCEMjOMa2tX0EHqiPrceMmGtK6We-4dTzNDvXEyGKzIR_MR60doB0oUpGRLOxXq9L1nL6ZjpiCU1g2</string>
  <string>ueK6Q6reM_ZUjXWBXFyfCiuh0dqNyhq7i-pAzxW5eUHR127_K1hxwtd5FeFvXm1M-YisRgJ73si5gXOUNRlY_g2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RefreshTokens {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RefreshTokens"]));
            }
            set {
                this["RefreshTokens"] = value;
            }
        }
    }
}
