//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dgmAttributeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dgmAttributeType()
        {
            this.dgmTypeAttributes = new HashSet<dgmTypeAttribute>();
            this.dgmEffectsModifierInfoes = new HashSet<dgmEffectsModifierInfo>();
            this.dgmEffectsModifierInfoes1 = new HashSet<dgmEffectsModifierInfo>();
        }
    
        public short attributeID { get; set; }
        public string attributeName { get; set; }
        public string description { get; set; }
        public Nullable<int> iconID { get; set; }
        public Nullable<double> defaultValue { get; set; }
        public Nullable<bool> published { get; set; }
        public string displayName { get; set; }
        public Nullable<byte> unitID { get; set; }
        public Nullable<bool> stackable { get; set; }
        public Nullable<bool> highIsGood { get; set; }
        public Nullable<byte> categoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dgmTypeAttribute> dgmTypeAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dgmEffectsModifierInfo> dgmEffectsModifierInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dgmEffectsModifierInfo> dgmEffectsModifierInfoes1 { get; set; }
    }
}
