//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dgmEffectsModifierInfo
    {
        public short effectID { get; set; }
        public string func { get; set; }
        public Nullable<int> groupID { get; set; }
        public short modifiedAttributeID { get; set; }
        public short modifyingAttributeID { get; set; }
        public int @operator { get; set; }
        public Nullable<int> skillTypeID { get; set; }
        public Nullable<int> secondEffectID { get; set; }
    
        public virtual dgmAttributeType modifiedAttribute { get; set; }
        public virtual dgmAttributeType modifyingAttribute { get; set; }
        public virtual dgmEffect dgmEffect { get; set; }
    }
}
