//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dgmTypeAttribute
    {
        public int typeID { get; set; }
        public short attributeID { get; set; }
        public Nullable<int> valueInt { get; set; }
        public Nullable<double> valueFloat { get; set; }
    
        public virtual dgmAttributeType dgmAttributeType { get; set; }
        public virtual invType invType { get; set; }
    }
}
