//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE
{
    using System;
    using System.Collections.Generic;
    
    public partial class industryactivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public industryactivity()
        {
            this.industryactivitymaterials = new HashSet<industryactivitymaterial>();
            this.industryactivityprobabilities = new HashSet<industryactivityprobability>();
            this.industryactivityproducts = new HashSet<industryactivityproduct>();
        }
    
        public int typeID { get; set; }
        public int activityID { get; set; }
        public Nullable<int> time { get; set; }
    
        public virtual invtype blueprint_invtype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryactivitymaterial> industryactivitymaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryactivityprobability> industryactivityprobabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryactivityproduct> industryactivityproducts { get; set; }
    }
}
