//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class industryActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public industryActivity()
        {
            this.industryActivityMaterials = new HashSet<industryActivityMaterial>();
            this.industryActivityProducts = new HashSet<industryActivityProduct>();
        }
    
        public int blueprintTypeID { get; set; }
        public byte activityID { get; set; }
        public Nullable<int> time { get; set; }
    
        public virtual invType blueprintType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryActivityMaterial> industryActivityMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryActivityProduct> industryActivityProducts { get; set; }
    }
}
