//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE
{
    using System;
    using System.Collections.Generic;
    
    public partial class industryblueprint
    {
        public int typeID { get; set; }
        public Nullable<int> maxProductionLimit { get; set; }
    }
}
