//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class invGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invGroup()
        {
            this.invTypes = new HashSet<invType>();
        }
    
        public int groupID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string groupName { get; set; }
        public Nullable<bool> published { get; set; }
        public Nullable<bool> anchorable { get; set; }
        public Nullable<bool> anchored { get; set; }
        public Nullable<bool> fittableNonSingleton { get; set; }
        public Nullable<bool> useBasePrice { get; set; }
        public Nullable<int> iconID { get; set; }
    
        public virtual invCategory invCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invType> invTypes { get; set; }
    }
}
