//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE
{
    using System;
    using System.Collections.Generic;
    
    public partial class invtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invtype()
        {
            this.blueprint_industryactivities = new HashSet<industryactivity>();
            this.blueprint_industryactivitymaterials = new HashSet<industryactivitymaterial>();
            this.materials_industryactivitymaterials = new HashSet<industryactivitymaterial>();
            this.blueprint_industryactivityprobabilities = new HashSet<industryactivityprobability>();
            this.blueprint_industryactivityproducts = new HashSet<industryactivityproduct>();
            this.product_industryactivityproducts = new HashSet<industryactivityproduct>();
        }
    
        public int typeID { get; set; }
        public Nullable<int> groupID { get; set; }
        public string typeName { get; set; }
        public string typeDescription { get; set; }
        public Nullable<double> mass { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> capacity { get; set; }
        public Nullable<int> portionSize { get; set; }
        public Nullable<int> raceID { get; set; }
        public Nullable<decimal> basePrice { get; set; }
        public Nullable<byte> published { get; set; }
        public Nullable<int> marketGroupID { get; set; }
        public Nullable<int> iconID { get; set; }
        public Nullable<int> soundID { get; set; }
        public Nullable<int> graphicID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryactivity> blueprint_industryactivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryactivitymaterial> blueprint_industryactivitymaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryactivitymaterial> materials_industryactivitymaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryactivityprobability> blueprint_industryactivityprobabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryactivityproduct> blueprint_industryactivityproducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<industryactivityproduct> product_industryactivityproducts { get; set; }
        public virtual invmarketgroup invmarketgroup { get; set; }

		public override string ToString()
		{
			return this.typeName;
		}

		public override bool Equals(object obj)
		{
			var item = obj as invtype;

			if (item == null)
			{
				return false;
			}

			return this.typeID == item.typeID;
		}

		public override int GetHashCode()
		{
			return typeID.GetHashCode();
		}

	}
}
