//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapSolarSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mapSolarSystem()
        {
            this.jumpsFrom = new HashSet<mapSolarSystemJump>();
            this.jumpsTo = new HashSet<mapSolarSystemJump>();
        }
    
        public int solarSystemID { get; set; }
        public string solarSystemName { get; set; }
        public Nullable<int> regionID { get; set; }
        public Nullable<int> constellationID { get; set; }
        public Nullable<float> x { get; set; }
        public Nullable<float> y { get; set; }
        public Nullable<float> z { get; set; }
        public Nullable<float> x_Min { get; set; }
        public Nullable<float> x_Max { get; set; }
        public Nullable<float> y_Min { get; set; }
        public Nullable<float> y_Max { get; set; }
        public Nullable<float> z_Min { get; set; }
        public Nullable<float> z_Max { get; set; }
        public Nullable<float> luminosity { get; set; }
        public Nullable<bool> border { get; set; }
        public Nullable<bool> corridor { get; set; }
        public Nullable<bool> fringe { get; set; }
        public Nullable<bool> hub { get; set; }
        public Nullable<bool> international { get; set; }
        public Nullable<bool> regional { get; set; }
        public Nullable<float> security { get; set; }
        public Nullable<int> factionID { get; set; }
        public Nullable<float> radius { get; set; }
        public Nullable<int> sunTypeID { get; set; }
        public string securityClass { get; set; }
        public Nullable<int> solarSystemNameID { get; set; }
        public string visualEffect { get; set; }
        public Nullable<int> descriptionID { get; set; }
    
        public virtual mapConstellation mapConstellation { get; set; }
        public virtual mapRegion mapRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mapSolarSystemJump> jumpsFrom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mapSolarSystemJump> jumpsTo { get; set; }
    }
}
